/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace IFlyoverConfigurations {
  export type ConfirmationTierStruct = {
    maxAmount: BigNumberish;
    confirmations: BigNumberish;
  };

  export type ConfirmationTierStructOutput = [BigNumber, BigNumber] & {
    maxAmount: BigNumber;
    confirmations: BigNumber;
  };

  export type PegConfigurationStruct = {
    fixedFee: BigNumberish;
    percentageFee: BigNumberish;
    minAmount: BigNumberish;
    maxAmount: BigNumberish;
    registrantFee: BigNumberish;
    confirmationTiers: IFlyoverConfigurations.ConfirmationTierStruct[];
  };

  export type PegConfigurationStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    IFlyoverConfigurations.ConfirmationTierStructOutput[]
  ] & {
    fixedFee: BigNumber;
    percentageFee: BigNumber;
    minAmount: BigNumber;
    maxAmount: BigNumber;
    registrantFee: BigNumber;
    confirmationTiers: IFlyoverConfigurations.ConfirmationTierStructOutput[];
  };

  export type PegOutConfigurationStruct = {
    fixedFee: BigNumberish;
    percentageFee: BigNumberish;
    minAmount: BigNumberish;
    maxAmount: BigNumberish;
    confirmationTiers: IFlyoverConfigurations.ConfirmationTierStruct[];
    penaltyFee: BigNumberish;
    claimWindow: BigNumberish;
    claimWindowBlocks: BigNumberish;
    callTime: BigNumberish;
    expireTime: BigNumberish;
    expireBlocks: BigNumberish;
    maxMinerFee: BigNumberish;
  };

  export type PegOutConfigurationStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    IFlyoverConfigurations.ConfirmationTierStructOutput[],
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    fixedFee: BigNumber;
    percentageFee: BigNumber;
    minAmount: BigNumber;
    maxAmount: BigNumber;
    confirmationTiers: IFlyoverConfigurations.ConfirmationTierStructOutput[];
    penaltyFee: BigNumber;
    claimWindow: BigNumber;
    claimWindowBlocks: BigNumber;
    callTime: BigNumber;
    expireTime: BigNumber;
    expireBlocks: BigNumber;
    maxMinerFee: BigNumber;
  };
}

export interface FlyoverConfigurationsInterface extends utils.Interface {
  functions: {
    "applyChange()": FunctionFragment;
    "applyPegOutChange()": FunctionFragment;
    "calculatePegInFee(uint256)": FunctionFragment;
    "calculatePegOutFee(uint256)": FunctionFragment;
    "getPegInConfiguration()": FunctionFragment;
    "getPegOutConfiguration()": FunctionFragment;
    "getRequiredPegInBtcConfirmations(uint256)": FunctionFragment;
    "getRequiredPegOutBtcConfirmations(uint256)": FunctionFragment;
    "queueChange((uint256,uint256,uint256,uint256,uint256,(uint256,uint256)[]))": FunctionFragment;
    "queuePegOutChange((uint256,uint256,uint256,uint256,(uint256,uint256)[],uint256,uint256,uint256,uint256,uint256,uint256,uint256))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "applyChange"
      | "applyPegOutChange"
      | "calculatePegInFee"
      | "calculatePegOutFee"
      | "getPegInConfiguration"
      | "getPegOutConfiguration"
      | "getRequiredPegInBtcConfirmations"
      | "getRequiredPegOutBtcConfirmations"
      | "queueChange"
      | "queuePegOutChange"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "applyChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "applyPegOutChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePegInFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePegOutFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPegInConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPegOutConfiguration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredPegInBtcConfirmations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequiredPegOutBtcConfirmations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "queueChange",
    values: [IFlyoverConfigurations.PegConfigurationStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "queuePegOutChange",
    values: [IFlyoverConfigurations.PegOutConfigurationStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "applyChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyPegOutChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePegInFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePegOutFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPegInConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPegOutConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredPegInBtcConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequiredPegOutBtcConfirmations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queuePegOutChange",
    data: BytesLike
  ): Result;

  events: {};
}

export interface FlyoverConfigurations extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FlyoverConfigurationsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    applyChange(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    applyPegOutChange(
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    calculatePegInFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fee: BigNumber }>;

    calculatePegOutFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fee: BigNumber }>;

    getPegInConfiguration(
      overrides?: CallOverrides
    ): Promise<
      [IFlyoverConfigurations.PegConfigurationStructOutput] & {
        configuration: IFlyoverConfigurations.PegConfigurationStructOutput;
      }
    >;

    getPegOutConfiguration(
      overrides?: CallOverrides
    ): Promise<
      [IFlyoverConfigurations.PegOutConfigurationStructOutput] & {
        configuration: IFlyoverConfigurations.PegOutConfigurationStructOutput;
      }
    >;

    getRequiredPegInBtcConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { confirmations: BigNumber }>;

    getRequiredPegOutBtcConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { confirmations: BigNumber }>;

    queueChange(
      newConfiguration: IFlyoverConfigurations.PegConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    queuePegOutChange(
      newConfiguration: IFlyoverConfigurations.PegOutConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  applyChange(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  applyPegOutChange(
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  calculatePegInFee(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  calculatePegOutFee(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getPegInConfiguration(
    overrides?: CallOverrides
  ): Promise<IFlyoverConfigurations.PegConfigurationStructOutput>;

  getPegOutConfiguration(
    overrides?: CallOverrides
  ): Promise<IFlyoverConfigurations.PegOutConfigurationStructOutput>;

  getRequiredPegInBtcConfirmations(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getRequiredPegOutBtcConfirmations(
    amount: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  queueChange(
    newConfiguration: IFlyoverConfigurations.PegConfigurationStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  queuePegOutChange(
    newConfiguration: IFlyoverConfigurations.PegOutConfigurationStruct,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    applyChange(overrides?: CallOverrides): Promise<void>;

    applyPegOutChange(overrides?: CallOverrides): Promise<void>;

    calculatePegInFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculatePegOutFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPegInConfiguration(
      overrides?: CallOverrides
    ): Promise<IFlyoverConfigurations.PegConfigurationStructOutput>;

    getPegOutConfiguration(
      overrides?: CallOverrides
    ): Promise<IFlyoverConfigurations.PegOutConfigurationStructOutput>;

    getRequiredPegInBtcConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRequiredPegOutBtcConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queueChange(
      newConfiguration: IFlyoverConfigurations.PegConfigurationStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    queuePegOutChange(
      newConfiguration: IFlyoverConfigurations.PegOutConfigurationStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    applyChange(overrides?: Overrides & { from?: string }): Promise<BigNumber>;

    applyPegOutChange(
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    calculatePegInFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calculatePegOutFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPegInConfiguration(overrides?: CallOverrides): Promise<BigNumber>;

    getPegOutConfiguration(overrides?: CallOverrides): Promise<BigNumber>;

    getRequiredPegInBtcConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRequiredPegOutBtcConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    queueChange(
      newConfiguration: IFlyoverConfigurations.PegConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    queuePegOutChange(
      newConfiguration: IFlyoverConfigurations.PegOutConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    applyChange(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    applyPegOutChange(
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    calculatePegInFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calculatePegOutFee(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPegInConfiguration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPegOutConfiguration(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRequiredPegInBtcConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRequiredPegOutBtcConfirmations(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    queueChange(
      newConfiguration: IFlyoverConfigurations.PegConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    queuePegOutChange(
      newConfiguration: IFlyoverConfigurations.PegOutConfigurationStruct,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
