/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export declare namespace Quotes {
  export type PegOutQuoteStruct = {
    chainId: BigNumberish;
    callFee: BigNumberish;
    penaltyFee: BigNumberish;
    value: BigNumberish;
    gasFee: BigNumberish;
    lbcAddress: string;
    lpRskAddress: string;
    rskRefundAddress: string;
    nonce: BigNumberish;
    agreementTimestamp: BigNumberish;
    depositDateLimit: BigNumberish;
    transferTime: BigNumberish;
    expireDate: BigNumberish;
    expireBlock: BigNumberish;
    depositConfirmations: BigNumberish;
    transferConfirmations: BigNumberish;
    depositAddress: BytesLike;
    btcRefundAddress: BytesLike;
    lpBtcAddress: BytesLike;
  };

  export type PegOutQuoteStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    number,
    number,
    number,
    number,
    number,
    number,
    number,
    string,
    string,
    string
  ] & {
    chainId: BigNumber;
    callFee: BigNumber;
    penaltyFee: BigNumber;
    value: BigNumber;
    gasFee: BigNumber;
    lbcAddress: string;
    lpRskAddress: string;
    rskRefundAddress: string;
    nonce: BigNumber;
    agreementTimestamp: number;
    depositDateLimit: number;
    transferTime: number;
    expireDate: number;
    expireBlock: number;
    depositConfirmations: number;
    transferConfirmations: number;
    depositAddress: string;
    btcRefundAddress: string;
    lpBtcAddress: string;
  };
}

export interface PegoutInterface extends utils.Interface {
  functions: {
    "depositPegOut((uint256,uint256,uint256,uint256,uint256,address,address,address,int64,uint32,uint32,uint32,uint32,uint32,uint16,uint16,bytes,bytes,bytes),bytes)": FunctionFragment;
    "dustThreshold()": FunctionFragment;
    "eip712Domain()": FunctionFragment;
    "getBalance(address)": FunctionFragment;
    "hashPegOutQuote((uint256,uint256,uint256,uint256,uint256,address,address,address,int64,uint32,uint32,uint32,uint32,uint32,uint16,uint16,bytes,bytes,bytes))": FunctionFragment;
    "hashPegOutQuoteEIP712((uint256,uint256,uint256,uint256,uint256,address,address,address,int64,uint32,uint32,uint32,uint32,uint32,uint16,uint16,bytes,bytes,bytes))": FunctionFragment;
    "isQuoteCompleted(bytes32)": FunctionFragment;
    "pauseStatus()": FunctionFragment;
    "refundPegOut(bytes32,bytes,bytes32,uint256,bytes32[])": FunctionFragment;
    "refundUserPegOut(bytes32)": FunctionFragment;
    "validatePegout(bytes32,bytes)": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "depositPegOut"
      | "dustThreshold"
      | "eip712Domain"
      | "getBalance"
      | "hashPegOutQuote"
      | "hashPegOutQuoteEIP712"
      | "isQuoteCompleted"
      | "pauseStatus"
      | "refundPegOut"
      | "refundUserPegOut"
      | "validatePegout"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositPegOut",
    values: [Quotes.PegOutQuoteStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dustThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getBalance", values: [string]): string;
  encodeFunctionData(
    functionFragment: "hashPegOutQuote",
    values: [Quotes.PegOutQuoteStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "hashPegOutQuoteEIP712",
    values: [Quotes.PegOutQuoteStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isQuoteCompleted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "refundPegOut",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "refundUserPegOut",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validatePegout",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositPegOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dustThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashPegOutQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashPegOutQuoteEIP712",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isQuoteCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundPegOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "refundUserPegOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validatePegout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "BalanceDecrease(address,uint256)": EventFragment;
    "BalanceIncrease(address,uint256)": EventFragment;
    "EIP712DomainChanged()": EventFragment;
    "PegOutChangePaid(bytes32,address,uint256)": EventFragment;
    "PegOutDeposit(bytes32,address,uint256,uint256)": EventFragment;
    "PegOutRefunded(bytes32)": EventFragment;
    "PegOutUserRefunded(bytes32,address,uint256)": EventFragment;
    "Withdrawal(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BalanceDecrease"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BalanceIncrease"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EIP712DomainChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutChangePaid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutDeposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutRefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PegOutUserRefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdrawal"): EventFragment;
}

export interface BalanceDecreaseEventObject {
  dest: string;
  amount: BigNumber;
}
export type BalanceDecreaseEvent = TypedEvent<
  [string, BigNumber],
  BalanceDecreaseEventObject
>;

export type BalanceDecreaseEventFilter = TypedEventFilter<BalanceDecreaseEvent>;

export interface BalanceIncreaseEventObject {
  dest: string;
  amount: BigNumber;
}
export type BalanceIncreaseEvent = TypedEvent<
  [string, BigNumber],
  BalanceIncreaseEventObject
>;

export type BalanceIncreaseEventFilter = TypedEventFilter<BalanceIncreaseEvent>;

export interface EIP712DomainChangedEventObject {}
export type EIP712DomainChangedEvent = TypedEvent<
  [],
  EIP712DomainChangedEventObject
>;

export type EIP712DomainChangedEventFilter =
  TypedEventFilter<EIP712DomainChangedEvent>;

export interface PegOutChangePaidEventObject {
  quoteHash: string;
  userAddress: string;
  change: BigNumber;
}
export type PegOutChangePaidEvent = TypedEvent<
  [string, string, BigNumber],
  PegOutChangePaidEventObject
>;

export type PegOutChangePaidEventFilter =
  TypedEventFilter<PegOutChangePaidEvent>;

export interface PegOutDepositEventObject {
  quoteHash: string;
  sender: string;
  timestamp: BigNumber;
  amount: BigNumber;
}
export type PegOutDepositEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  PegOutDepositEventObject
>;

export type PegOutDepositEventFilter = TypedEventFilter<PegOutDepositEvent>;

export interface PegOutRefundedEventObject {
  quoteHash: string;
}
export type PegOutRefundedEvent = TypedEvent<
  [string],
  PegOutRefundedEventObject
>;

export type PegOutRefundedEventFilter = TypedEventFilter<PegOutRefundedEvent>;

export interface PegOutUserRefundedEventObject {
  quoteHash: string;
  userAddress: string;
  value: BigNumber;
}
export type PegOutUserRefundedEvent = TypedEvent<
  [string, string, BigNumber],
  PegOutUserRefundedEventObject
>;

export type PegOutUserRefundedEventFilter =
  TypedEventFilter<PegOutUserRefundedEvent>;

export interface WithdrawalEventObject {
  from: string;
  to: string;
  amount: BigNumber;
}
export type WithdrawalEvent = TypedEvent<
  [string, string, BigNumber],
  WithdrawalEventObject
>;

export type WithdrawalEventFilter = TypedEventFilter<WithdrawalEvent>;

export interface Pegout extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PegoutInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositPegOut(
      quote: Quotes.PegOutQuoteStruct,
      signature: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<ContractTransaction>;

    dustThreshold(overrides?: CallOverrides): Promise<[BigNumber]>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    getBalance(addr: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    hashPegOutQuote(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    hashPegOutQuoteEIP712(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isQuoteCompleted(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    pauseStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber] & {
        isPaused: boolean;
        reason: string;
        since: BigNumber;
      }
    >;

    refundPegOut(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      btcBlockHeaderHash: BytesLike,
      merkleBranchPath: BigNumberish,
      merkleBranchHashes: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    refundUserPegOut(
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    validatePegout(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [Quotes.PegOutQuoteStructOutput] & {
        quote: Quotes.PegOutQuoteStructOutput;
      }
    >;

    withdraw(
      addr: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;
  };

  depositPegOut(
    quote: Quotes.PegOutQuoteStruct,
    signature: BytesLike,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractTransaction>;

  dustThreshold(overrides?: CallOverrides): Promise<BigNumber>;

  eip712Domain(
    overrides?: CallOverrides
  ): Promise<
    [string, string, string, BigNumber, string, string, BigNumber[]] & {
      fields: string;
      name: string;
      version: string;
      chainId: BigNumber;
      verifyingContract: string;
      salt: string;
      extensions: BigNumber[];
    }
  >;

  getBalance(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

  hashPegOutQuote(
    quote: Quotes.PegOutQuoteStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  hashPegOutQuoteEIP712(
    quote: Quotes.PegOutQuoteStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  isQuoteCompleted(
    quoteHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  pauseStatus(
    overrides?: CallOverrides
  ): Promise<
    [boolean, string, BigNumber] & {
      isPaused: boolean;
      reason: string;
      since: BigNumber;
    }
  >;

  refundPegOut(
    quoteHash: BytesLike,
    btcTx: BytesLike,
    btcBlockHeaderHash: BytesLike,
    merkleBranchPath: BigNumberish,
    merkleBranchHashes: BytesLike[],
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  refundUserPegOut(
    quoteHash: BytesLike,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  validatePegout(
    quoteHash: BytesLike,
    btcTx: BytesLike,
    overrides?: CallOverrides
  ): Promise<Quotes.PegOutQuoteStructOutput>;

  withdraw(
    addr: string,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  callStatic: {
    depositPegOut(
      quote: Quotes.PegOutQuoteStruct,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    dustThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    eip712Domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, string, BigNumber, string, string, BigNumber[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
        salt: string;
        extensions: BigNumber[];
      }
    >;

    getBalance(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    hashPegOutQuote(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    hashPegOutQuoteEIP712(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    isQuoteCompleted(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    pauseStatus(
      overrides?: CallOverrides
    ): Promise<
      [boolean, string, BigNumber] & {
        isPaused: boolean;
        reason: string;
        since: BigNumber;
      }
    >;

    refundPegOut(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      btcBlockHeaderHash: BytesLike,
      merkleBranchPath: BigNumberish,
      merkleBranchHashes: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    refundUserPegOut(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    validatePegout(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      overrides?: CallOverrides
    ): Promise<Quotes.PegOutQuoteStructOutput>;

    withdraw(
      addr: string,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BalanceDecrease(address,uint256)"(
      dest?: string | null,
      amount?: BigNumberish | null
    ): BalanceDecreaseEventFilter;
    BalanceDecrease(
      dest?: string | null,
      amount?: BigNumberish | null
    ): BalanceDecreaseEventFilter;

    "BalanceIncrease(address,uint256)"(
      dest?: string | null,
      amount?: BigNumberish | null
    ): BalanceIncreaseEventFilter;
    BalanceIncrease(
      dest?: string | null,
      amount?: BigNumberish | null
    ): BalanceIncreaseEventFilter;

    "EIP712DomainChanged()"(): EIP712DomainChangedEventFilter;
    EIP712DomainChanged(): EIP712DomainChangedEventFilter;

    "PegOutChangePaid(bytes32,address,uint256)"(
      quoteHash?: BytesLike | null,
      userAddress?: string | null,
      change?: BigNumberish | null
    ): PegOutChangePaidEventFilter;
    PegOutChangePaid(
      quoteHash?: BytesLike | null,
      userAddress?: string | null,
      change?: BigNumberish | null
    ): PegOutChangePaidEventFilter;

    "PegOutDeposit(bytes32,address,uint256,uint256)"(
      quoteHash?: BytesLike | null,
      sender?: string | null,
      timestamp?: BigNumberish | null,
      amount?: null
    ): PegOutDepositEventFilter;
    PegOutDeposit(
      quoteHash?: BytesLike | null,
      sender?: string | null,
      timestamp?: BigNumberish | null,
      amount?: null
    ): PegOutDepositEventFilter;

    "PegOutRefunded(bytes32)"(
      quoteHash?: BytesLike | null
    ): PegOutRefundedEventFilter;
    PegOutRefunded(quoteHash?: BytesLike | null): PegOutRefundedEventFilter;

    "PegOutUserRefunded(bytes32,address,uint256)"(
      quoteHash?: BytesLike | null,
      userAddress?: string | null,
      value?: BigNumberish | null
    ): PegOutUserRefundedEventFilter;
    PegOutUserRefunded(
      quoteHash?: BytesLike | null,
      userAddress?: string | null,
      value?: BigNumberish | null
    ): PegOutUserRefundedEventFilter;

    "Withdrawal(address,address,uint256)"(
      from?: string | null,
      to?: string | null,
      amount?: BigNumberish | null
    ): WithdrawalEventFilter;
    Withdrawal(
      from?: string | null,
      to?: string | null,
      amount?: BigNumberish | null
    ): WithdrawalEventFilter;
  };

  estimateGas: {
    depositPegOut(
      quote: Quotes.PegOutQuoteStruct,
      signature: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<BigNumber>;

    dustThreshold(overrides?: CallOverrides): Promise<BigNumber>;

    eip712Domain(overrides?: CallOverrides): Promise<BigNumber>;

    getBalance(addr: string, overrides?: CallOverrides): Promise<BigNumber>;

    hashPegOutQuote(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashPegOutQuoteEIP712(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isQuoteCompleted(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    pauseStatus(overrides?: CallOverrides): Promise<BigNumber>;

    refundPegOut(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      btcBlockHeaderHash: BytesLike,
      merkleBranchPath: BigNumberish,
      merkleBranchHashes: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    refundUserPegOut(
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    validatePegout(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdraw(
      addr: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositPegOut(
      quote: Quotes.PegOutQuoteStruct,
      signature: BytesLike,
      overrides?: PayableOverrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    dustThreshold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    eip712Domain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBalance(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashPegOutQuote(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashPegOutQuoteEIP712(
      quote: Quotes.PegOutQuoteStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isQuoteCompleted(
      quoteHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pauseStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    refundPegOut(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      btcBlockHeaderHash: BytesLike,
      merkleBranchPath: BigNumberish,
      merkleBranchHashes: BytesLike[],
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    refundUserPegOut(
      quoteHash: BytesLike,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    validatePegout(
      quoteHash: BytesLike,
      btcTx: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      addr: string,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;
  };
}
